[workspace]
members = [
    "crates/nwords",
    "crates/nwords-bip39-seed",
    "crates/nwords-cli",
    "crates/nwords-core",
    "crates/nwords-schemes",
    "crates/nwords-tools",
    "crates/nwords-web",
    "crates/nwords-wordlists",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
repository = "https://github.com/y4le/nwords"
homepage = "https://github.com/y4le/nwords"
readme = "README.md"
