// Emitted from tests/vectors/semantic-wordlists/weather/nwords-weather.txt.
// Authored in-repo; see that directory's README for seed references.

#[rustfmt::skip]
pub(crate) const WEATHER: &[&str] = &[
    "balmy",
    "blustery",
    "breezy",
    "bright",
    "brisk",
    "chilly",
    "clear",
    "cloudy",
    "cold",
    "cool",
    "crisp",
    "damp",
    "dewy",
    "drizzly",
    "dry",
    "dusky",
    "fair",
    "foggy",
    "frosty",
    "gusty",
    "hazy",
    "hot",
    "humid",
    "icy",
    "mild",
    "misty",
    "muggy",
    "overcast",
    "rainy",
    "shaded",
    "showery",
    "sleety",
    "snowy",
    "stormy",
    "sunny",
    "thawing",
    "tropical",
    "warm",
    "windy",
    "wintry",
];
