[package]
name = "nwords-schemes"
description = "Ready-made schemes for nwords."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["std", "bip39-english", "positional"]
std = ["nwords-core/std", "nwords-wordlists?/std"]
alloc = ["nwords-core/alloc"]
bip39-english = [
    "alloc",
    "dep:nwords-wordlists",
    "dep:sha2",
    "nwords-wordlists/bip39-english",
]
bip39-japanese = [
    "bip39-english",
    "dep:unicode-normalization",
    "nwords-wordlists/bip39-japanese",
]
positional = ["alloc", "nwords-core/stats"]

[dependencies]
nwords-core = { version = "0.1.0", path = "../nwords-core", default-features = false }
nwords-wordlists = { version = "0.1.0", path = "../nwords-wordlists", default-features = false, optional = true }
sha2 = { version = "0.10.9", default-features = false, optional = true }
unicode-normalization = { version = "0.1.25", default-features = false, optional = true }
