[package]
name = "nwords-bip39-seed"
description = "BIP-39 seed derivation for nwords."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]

